M2Team/NanaZip

- SevenZip/Lang/pl.txt
> Update Polish translation

- ReadMe.md
@MouriNaruto are all features of 7-Zip 22.01 applied? if yes let's update the README 🙂
> Update README: NanaZip is based on 7-Zip 22.01

- ReadMe.md
Generated with:
https://github.com/JasonWei512/Microsoft-Store-Badge
----------
I also made a GitHub action to upload Microsoft Store-signed MSIX packages to GitHub release. It might be useful to you.
https://github.com/JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release
> Add a store rating badge to ReadMe.md

- NanaZipPackage/Strings/pl/Legacy.resw
> Updated Polish translation

- NanaZip.UI.Modern/NanaZip.Modern.vcxproj
- NanaZip.UI.Modern/NanaZip.Modern.vcxproj.filters
- NanaZip.UI.Modern/Strings/pl/MainWindowToolBarPage.resw
- NanaZip.UI.Modern/Strings/pl/SponsorPage.resw
Polish translation for Sponsor dialog.
> Polish translation for Sponsor dialog.

- ReadMe.md
Add instructions on how to specify the license file, in order to allow fully offline installations.
> [Docs] README: Demonstrate license file usage

- NanaZip.UI.Modern/MainWindowToolBarPage.cpp
- NanaZip.UI.Modern/MainWindowToolBarPage.h
To make it more visually distinct.
> Shadow for sponsorship button.

- NanaZip.Shared/ModernWin32FileBrowser.cpp
> Don't fail ModernSHBrowseForFolderW when DefaultFolder cannot be set.

- NanaZip.UI.Modern/NanaZip.ShellExtension.cpp
I forgot to add this code for Shell Extension...
> Smart Extraction: Bug fix

- NanaZipPackage/Strings/pt-br/Legacy.resw
Update the language to be more suitable
> Update Legacy.resw pt-BR Update the language to be more suitable

- NanaZipPackage/Strings/pl/Legacy.resw
The new strings have been translated into Polish.
> Update of the Polish translation

- NanaZipPackage/Strings/ru/Legacy.resw
- NanaZipPackage/Strings/uk/Legacy.resw
Added missing localization strings for Ukrainian and Russian translation.
> Update Ukrainian and Russian localization

- NanaZip.UI.Modern/Strings/hu/MainWindowToolBarPage.resw
- NanaZip.UI.Modern/Strings/hu/SponsorPage.resw
Adding 2 Hungarian language files for UI Modern.
> UI Modern Hungarian language files

- NanaZipPackage/Package.appxmanifest
These formats are simply renamed ZIP/RAR files.
> Add support for CBR/CBZ extensions.

- NanaZip.ModernExperience/AddressBar.cpp
- NanaZip.ModernExperience/AddressBar.h
- NanaZip.ModernExperience/AddressBarTemplate.xaml
Removes much boilerplate code.
> Use binding for address bar properties

- NanaZip.Shared/DllBlock.cpp
Fix #645.
Also do a bit of reorganization of the DLL blocklist.
> Block Proxifier

- NanaZipPackage/Strings/el/Legacy.resw
- NanaZipPackage/Strings/en/Legacy.resw
- NanaZipPackage/Strings/hu/Legacy.resw
- NanaZipPackage/Strings/nl/Legacy.resw
- NanaZipPackage/Strings/pl/Legacy.resw
- NanaZipPackage/Strings/pt-br/Legacy.resw
- NanaZipPackage/Strings/ru/Legacy.resw
- NanaZipPackage/Strings/sq/Legacy.resw
- NanaZipPackage/Strings/uk/Legacy.resw
- NanaZipPackage/Strings/zh-Hans/Legacy.resw
- NanaZipPackage/Strings/zh-Hant/Legacy.resw
- Try to fix missing Resource1019 build warning.
- Reorder the out-of-order Resource3433. (which was actually my fault)
> Fix up string resources.

- NanaZip.Core/SevenZip/CPP/7zip/UI/Common/Extract.cpp
- NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Common/Extract.cpp
- NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Common/Extract.cpp
- NanaZip.Universal/SevenZip/CPP/7zip/UI/Common/Extract.cpp
Use std::set and wstring to solve issues.
This PR will fix #588 and close #591.
> Improve Smart Extraction

- NanaZip.Modern/MainWindowToolBarPage.cpp
> Initialize StoreContext later

- NanaZip.Modern/AboutPage.cpp
- NanaZip.Modern/InformationPage.cpp
- NanaZip.Modern/NanaZip.Modern.cpp
> Fix flickering XAML dialogs

- CONTRIBUTING.md
- Documents/People.md
> Fix Typoes
