ReadMe.md
Current shields.io-images show an error saying `no releases or repo not found`, because there are no releases that are not pre-releases.
Updated the links to use new urls provided by shields.io under categories [version](https://shields.io/category/version) and [downloads](https://shields.io/category/downloads).
The version shield will show the release name (`display_name=release`) instead of the tag name, and is using a custom color (`color=#a4a61d`)to indicate pre-release version. This can be removed later.
=> Update README.md. Use new links for shields.io

SevenZip/Lang/pl.txt
The current translation is too long to fit in the button.
=> Update Polish translation

NanaZipPackage/Package.appxmanifest
Starting from Windows 10 2004 (build 19041), if you add 
`<uap10:FileType>*</uap10:FileType>`
to the .appxmanifest file, the app can be selected in the "Open With" menu and in Properties>"Change..." for any file type.
This would allow users to associate NanaZip with less common archives which are actually ZIP files such as apk, cbz, jar, nupkg (I used to do the same with 7-Zip).
=> Allow NanaZip to be associated with any file type

SevenZip/CPP/7zip/UI/GUI/UpdateGUI.cpp
The default SFX file name in UpdateGUI.cpp was not updated.
=> Fix wrong default SFX stub file name.

NanaZipPackage/Package.appxmanifest
This is meant to be a fix for #193, #203 and other related issues.
Basically, when registering the shell extension via MSIX, Windows doesn't accept our current verb name "NanaZipShellExtension" for the "*" file type. The "Directory" file type and normal extensions (e.g. ".zip") work as normal. Registering our extension via [ExplorerCommandHandler](https://gist.github.com/dinhngtu/2be7222068241f6b0801e448dd8c442c) works normally with the same verb.
This patch changes the verb name of our shell extension to work around this issue.
I've tested this patch on the English version of Windows 10 21H2 and Windows 11. There might be some language-related behavior here so testing on other Windows languages would be appreciated.
=> Workaround for NanaZip not appearing in classic context menu.

SevenZip/CPP/7zip/UI/Common/CompressCall.cpp
Fixes #87. The code to automatically reload compression parameters from Registry didn't check for their validity, leading to invalid parameters being passed to the 7zip worker and therefore causing an out-of-memory error:
` a -i#7zMap[...] -t7z -mx=5 -md=4294967295b -ms=9223372036854775808b -mmt=4294967295 -sae -- [...]`
This patch validates the presence of each parameter before appending it to the parameter string.
=> Check 7z compression parameter validity upon start of compression.

NanaZip.Shared/Mitigations.cpp, NanaZip.Shared/Mitigations.h, SevenZip/CPP/7zip/UI/FileManager/FM.cpp
Fix #231.
ExplorerPatcher uses IAT hooking to intercept multiple shell API calls. This is not compatible with our dynamic code mitigation.
Enable dynamic code optout on the main FM thread to avoid startup crashes for now.
=> Opt out of dynamic code mitigation on main FM thread.

NanaZip.Shared/ModernWin32FileBrowser.cpp, NanaZip.Shared/NanaZip.Shared.ModernExperienceShims.props, NanaZip.Shared/NanaZip.Shared.ModernExperienceShims.vcxproj
Closes #251
Currently, I have implemented a shim for `SHBrowseForFolderW` that shows uses the Vista Common File Dialog. It does not understand every possible option that `SHBrowseForFolderW` takes, but it is good enough for the purposes of 7-Zip. It is not perfect, and there is one thing in particular that I am not too happy about:
7-Zip sets the dialog's default folder by setting in a custom message loop for the dialog, passing itself the path to the default folder as a string through `LPBROWSEINFOW.lParam`, and navigating to that path when the dialog is initialized. This method cannot work with IFileDialog, so this shim relies on the fact that 7-Zip always passes an `LPWSTR` to the message loop. If 7-Zip ever changes the way they use `SHBrowseForFolderW`, this shim will stop working …
=> Use modern IFileDialog for folder picker dialog 

NanaZip.Shared/Mitigations.cpp, NanaZip.Shared/Mitigations.h, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Console/MainAr.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/GUI/GUI.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Console/MainAr.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/GUI/GUI.cpp
NanaZipC and NanaZipG have no business creating child processes. Enable the corresponding mitigation policy in these programs.
=> Disable child processes in NanaZipC and NanaZipG.

NanaZip.Core/SevenZip/CPP/7zip/Archive/Common/HandlerOut.cpp
Fix #342.
7-Zip ZS sends all common compression parameters (`mt`, `memuse`) down to the individual handlers. However, this is broken in NanaZip (probably due to the 23.01 port?)
Don't pass anything except for the `mt` parameter to fix this issue.
=> Don't pass common compression props to handlers.

.github/workflows/BuildBinaries.yml
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update GitHub Actions for Node 20 support

NanaZip.Shared/DllBlock.cpp, NanaZip.Shared/DllBlock.h, NanaZip.Shared/Mitigations.cpp, NanaZip.Shared/Mitigations.h, NanaZip.Shared/NanaZip.Shared.Mitigations.vcxproj, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/FileManager/FM.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/FileManager/FM.cpp
To recall, #236 disabled the dynamic code mitigation on NanaZip's main FM thread due to an incompatibility with ExplorerPatcher.
This PR introduces in NanaZip FM a Detours hook of NtMapViewOfSection that inspects a mapped DLL's identity and denies the mapping if it belongs to a predefined list, which at the moment contains only ExplorerPatcher.
Also reenable dynamic code mitigation on main NanaZip FM thread.
Tested on Windows 11 with ExplorerPatcher installed.
Additional mitigations to follow.
=> Add DLL blocking hook for FM.

NanaZip.UI.Classic/NanaZip.vcxproj, NanaZip.UI.Classic/NanaZipShellExtension.vcxproj
NanaZip Classic and its shell extension still depend on WinRT `runtimeobject.lib`. Link them to this library.
=> Classic: Link with runtimeobject.lib.

NanaZipPackage/Strings/en/Legacy.resw, NanaZipPackage/Strings/pl/Legacy.resw
After some research, I figured out that these resources have their ID, so can be translated! 
Before:
After:
~~I didn't use any of these options and I didn't find much information, any context is appreciated. I make this PR as a draft now, to time as we gather more information. After that, we can also change them to something that sounds more clear (eg. Want ArcHistory to Keep a history of accessed archives), but I leave that decision to @MouriNaruto or NanaZip community.~~
Explanation was found [here](https://sourceforge.net/p/sevenzip/discussion/45797/thread/dc2ac53d/?limit=25) thanks to @MouriNaruto and @Dziubek. Below information may help for other translators.
I found some information in the book _"Windows Registry Forensics - Advanced Digital Forensic Analysis of the Windows …
=> Make the 7-Zip Zstandard branch's specific options translatable

NanaZip.Shared/DllBlock.cpp
Fixes #377, #408.
Sogou Pinyin's `resources.dll` does not have an export directory, which confuses the DLL blocker. Fix this issue.
Additionally, truncate overly-long or malformed DLL names.
Finally, block Transparent Flyout's `TFMain64.dll` from loading to fix a crash.
=> DllBlock: fix compatibility with Transparent Flyout and Sogou Pinyin

NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/FileManager/Panel.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/FileManager/Panel.h, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/FileManager/Panel.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/FileManager/Panel.h
Refer to #403.
When extracting without selecting anything, and if we're in the root of an archive, we should use the Extract dialog instead of the Copy To dialog.
=> Use Extract dialog when extracting without selection.

NanaZip.Shared/DllBlock.cpp, NanaZip.Shared/Mitigations.cpp, NanaZip.Shared/Mitigations.h
Compatibility fix for iFlyIME.
The procedure is as following:
- During NtMapViewOfSection hook: create a list of caller address ranges where dynamic code is allowed
- Hook VirtualAlloc(Ex)/VirtualProtect(Ex):
- Find caller IP with _ReturnAddress()
- If caller IP is in optout range, temporarily disable dynamic code optout before calling real function
- Hook NtUnmapViewOfSection to cleanup the address range list as needed
Tested with Explorer Patcher, Translucent Flyouts, Sogou Pinyin and iFlyIME.
=> DllBlock: hook VirtualAlloc/VirtualProtect for dynamic code exclusions

NanaZipPackage/Strings/zh-Hans/Legacy.resw
* Remove one extra space, there are already quotes. There are no spaces before other quotation marks.
* Change one full-width bracket to half-width to make it consistent with other places.
=> Fix simplified Chinese detail issues

NanaZip.UI.Modern/MainWindowToolBarPage.cpp, NanaZip.UI.Modern/MainWindowToolBarPage.h
Makes the shadow backwards compatible down to 17763 (which is enough for NanaZip Modern)
=> Use geometric clip instead of rectangular clip.

NanaZip.Core/SevenZip/CPP/7zip/UI/GUI/ExtractDialog.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/GUI/ExtractDialog.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/GUI/ExtractDialog.cpp
Even if the archive name checkbox in CExtractDialog is not checked, NanaZip appends the archive name to its extraction path anyway. Fix this issue by always splitting the extraction path in NanaZip.Windows.
=> Always split path in CExtractDialog.

NanaZip.UI.Modern/MainWindowToolBarPage.cpp, NanaZip.UI.Modern/SevenZip/CPP/Windows/ProcessUtils.cpp
This pr will fix #428, fix #543, fix #86...
And also added the code for hopefully workaround issue #462, further test needed.
=> Modern: Bring windows to foreground, fix opening from context menu cause window in background

BuildAllTargets.proj, NanaZip.ExtensionPackage/NanaZip.ExtensionPackage.Installer.iss, NanaZip.ExtensionPackage/NanaZip.ExtensionPackage.Installer.proj
Add NanaZip.ExtensionPackage in preparation for #502.
=> Add empty NanaZip.ExtensionPackage.

NanaZip.UI.Modern/SevenZip/CPP/Windows/Control/Dialog.cpp, NanaZip.UI.Modern/SevenZip/CPP/Windows/ProcessUtils.cpp, NanaZip.UI.Modern/SevenZip/CPP/Windows/Window.cpp, NanaZip.UI.Modern/SevenZip/CPP/Windows/Window.h
Call `BringToForeground` every time a dialog is created to make sure that dialogs don't get lost in the background.
Also move `BringToForeground` to `Window.cpp`.
=> Modern: bring dialogs to foreground

Documents/Policies.md, NanaZip.Core/SevenZip/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp, NanaZip.Core/SevenZip/CPP/7zip/UI/Common/Extract.h, NanaZip.Core/SevenZip/CPP/7zip/UI/Common/ExtractMode.h, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Agent/Agent.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Agent/Agent.h, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Common/Extract.h, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Common/ExtractMode.h, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/Common/ZipRegistry.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/FileManager/MenuPage.cpp, NanaZip.UI.Classic/SevenZip/CPP/7zip/UI/FileManager/Panel.h, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Agent/Agent.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Agent/Agent.h, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Common/Extract.h, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Common/ExtractMode.h, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/Common/ZipRegistry.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/FileManager/MenuPage.cpp, NanaZip.UI.Modern/SevenZip/CPP/7zip/UI/FileManager/Panel.h, NanaZipPackage/Strings/en/Legacy.resw, ReadMe.md
Fix #425.
- Set default MOTW mode (including NanaZip.Core) to Office files
- Add more unsafe file types (exe ps1 etc.) to MOTW extension list
- Add `HKLM\Software\NanaZip\Enforced` key for machine-wide enforcement of MOTW settings
=> MOTW enforcement changes

Documents/Policies.md, NanaZip.Shared/DllBlock.cpp, NanaZip.Shared/DllBlock.h, NanaZip.Shared/Mitigations.cpp, NanaZip.Shared/Mitigations.h
Workaround for #497 and #645.
Add an escape hatch to disable runtime mitigations by setting the value `DisableMitigations` in NanaZip policies (HKLM only).
For now only 2 values 0 (don't disable) and 1 (disable all) are defined.
=> Add DisableMitigations policy.

Documents/Policies.md, NanaZip.Core/SevenZip/CPP/7zip/Archive/ArchiveExports.cpp
Add a policy to control which archive handlers can be loaded by NanaZip.
With this policy, you can significantly limit the attack surface of NanaZip by blocking the parsing of unusual archive formats.
If AllowedHandlers is present, only the handlers specified in said list will be allowed.
If BlockedHandlers is present, the handlers specified in said list will be blocked. BlockedHandlers takes precedence over AllowedHandlers; i.e. handlers specified in BlockedHandlers will still be blocked even if they're specified in AllowedHandlers.
=> Implement archive handler restrictions policy

NanaZipPackage/Strings/de/Legacy.resw
This PR reduces the length of a single string in the german translation to fix an overflow in the UI
Before:
After:
=> Fix text overflow in German translation
